# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Hari Venkatesh
title: PhD Candidate in Economics
       Indian Institute of Technology Kharagpur
email: hari.venkatesh@iitkgp.ac.in
website: https://venkateshhari.github.io/

# Dark Mode (true/false/never)
darkmode: never
# Social links
# twitter_username: michele_fornino
#github_username:  venkateshhari
# facebook_username: michele.fornino
#linkedin_username: harivenkatesh8
#orcid_username: 0000-0002-9256-7252
# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a PhD Candidate in Economics at the Indian Institute of Technology Kharagpur. I will be graduating in July 2021. 
  
  My dissertation focuses on currency mismatches, predicting financial crises using machine learning algorithms, and analyze the financial effects of dollar appreciation on economic growth. I also work on issues related to international economics, trade, and investment

  - <b>Research interests: International Economics, Financial Crisis, Open Macroeconomics, Machine Learning.


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

# Dark mode
 # darkmode: false (options: true, false, never)
